name: Lint

on: [push, pull_request]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install black & isort
        run: pip install black isort

      - name: run linter
        uses: wearerequired/lint-action@v1
        with:
          black: true
          isort: true
          auto_fix: true
